### ISSUE TITLE
split of train.csv and val.csv

### ISSUE THREAD

**Issue by irkingmaker** [PaulAlbert31/SemiSupGrassClover#1]
Hello

I am trying to reproduce the results presented in the paper for GrassClover test set for "trusted data", and wanted to know what is the train.csv and val.csv that was used for the results. 

Thanks

**Comment by PaulAlbert31** [comment]
Hi,
Thank you for your interest in this work !
I attached the train/val csv files for the split I used  : 
[val.csv](https://github.com/PaulAlbert31/SemiSupGrassClover/files/11566939/val.csv)
[train.csv](https://github.com/PaulAlbert31/SemiSupGrassClover/files/11566941/train.csv)

**Comment by irkingmaker** [comment]
Thank you!
